#pragma config(Sensor, S3, reflectedValue, sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define THRESHOLD 30
#define LEFT_MOTOR motorC
#define RIGHT_MOTOR motorB

task main()
{
   nVolume = 4;

   for (int i = 1; i < 5; i++) {
      motor[LEFT_MOTOR] = 10;
      motor[RIGHT_MOTOR] = 10;

      while (SensorValue(reflectedValue) > THRESHOLD) {}

      if(i == 1){
      	playSound(soundBeepBeep);
      	sleep(500);
      }
      else if(i == 2){
      	playSound(soundBeepBeep);
      	sleep(500);
      	playSound(soundBeepBeep);
      	sleep(500);
      }
      else if(i == 3){
      	playSound(soundBeepBeep);
      	sleep(500);
      	playSound(soundBeepBeep);
      	sleep(500);
      	playSound(soundBeepBeep);
      	sleep(500);
      }
      else if(i == 4){
      	motor[LEFT_MOTOR] = 0;
   			motor[RIGHT_MOTOR] = 0;
      	playSound(soundBeepBeep);
      	sleep(500);
      	playSound(soundBeepBeep);
      	sleep(500);
      	playSound(soundBeepBeep);
      	sleep(500);
      	playSound(soundBeepBeep);
      	sleep(500);
      }
   }



}
