#pragma config(Sensor, S3,     color,          sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LEFT_MOTOR motorC
#define RIGHT_MOTOR motorB

task main()
{
	while(true){
		if(getColorName(color) == 5){
			motor[LEFT_MOTOR] = 70;
			motor[RIGHT_MOTOR] = 70;
		}
		else if(getColorName(color) == 2){
			motor[LEFT_MOTOR] = 10;
			motor[RIGHT_MOTOR] = -10;
			wait1Msec(1800);
			motor[LEFT_MOTOR] = 0;
			motor[RIGHT_MOTOR] = 0;
		}
		else if(getColorName(color) == 1){
			motor[LEFT_MOTOR] = -10;
			motor[RIGHT_MOTOR] = 10;
			wait1Msec(1800);
			motor[LEFT_MOTOR] = 0;
			motor[RIGHT_MOTOR] = 0;
		}
		else if(getColorName(color) == 3){
			motor[LEFT_MOTOR] = 0;
			motor[RIGHT_MOTOR] = 0;
			wait1Msec(500);
			motor[LEFT_MOTOR] = -10;
			motor[RIGHT_MOTOR] = -10;
			wait1Msec(1000);
			break;
		}

		motor[LEFT_MOTOR] = 15;
		motor[RIGHT_MOTOR] = 15;
		wait1Msec(1300);
	}
}
