#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LEFT_MOTOR motorC
#define RIGHT_MOTOR motorB

task main()
{
	int count = 0;
	int path[6] = {0, 1, 1, 0, 0, 1};

	while(1){
			while(getTouchValue(touchSensor) == 0){
				motor[RIGHT_MOTOR] = 25;
				motor[LEFT_MOTOR] = 25;
		  }

			if(getTouchValue(touchSensor) == 1 && path[count] == 0){
			motor[RIGHT_MOTOR] = -25;
			motor[LEFT_MOTOR] = -25;
			wait1Msec(1000);

			motor[RIGHT_MOTOR] = -38;
			motor[LEFT_MOTOR] = +38;
			wait1Msec(500);
			count++;
			}

			else if(getTouchValue(touchSensor) == 1 && path[count] == 1){
			motor[RIGHT_MOTOR] = -25;
			motor[LEFT_MOTOR] = -25;
			wait1Msec(1000);

			motor[RIGHT_MOTOR] = +38;
			motor[LEFT_MOTOR] = -38;
			wait1Msec(500);
			count++;
			}


	}

}
